name: Http_and_Web_Akso

services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8082:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Correct NGINX config path
      - ./tugas/html:/usr/share/tugas/html        # Correct path for static files
    networks:
      - app_network
    restart: always

  mysql:
    image: mysql:latest
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: composepassword    # Password for MySQL root user
      MYSQL_DATABASE: composedb               # Database name to create
      MYSQL_USER: composeuser                 # Custom MySQL user
      MYSQL_PASSWORD: composepass             # Password for custom user
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/    # Directory for initialization scripts
    networks:
      - app_network
    restart: always

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"                           # Correct default Redis port
    networks:
      - app_network

networks:
  app_network:
    driver: bridge







