name: Http_and_Web_Akso

services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8083:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Pastikan file ini ada
      - ./tugas/html:/usr/share/tugas/html        # Pastikan direktori ini ada
    networks:
      - app_network
    restart: always

  mysql:
    image: mysql:latest
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: composepassword    # Password untuk MySQL root user
      MYSQL_DATABASE: composedb               # Nama database yang akan dibuat
      MYSQL_USER: composeuser                 # Nama user MySQL
      MYSQL_PASSWORD: composepass             # Password user MySQL
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/    # Direktori untuk script inisialisasi
    networks:
      - app_network
    restart: always

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"                           # Port default Redis
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge
